//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISLER
    {
        public int ISID { get; set; }
        public string ISBASLIK { get; set; }
        public string ISACIKLAMA { get; set; }
        public Nullable<int> ISPERSONELID { get; set; }
        public Nullable<System.DateTime> ILETILENTARIH { get; set; }
        public Nullable<System.DateTime> YAPILANTARIH { get; set; }
        public Nullable<int> ISDURUMID { get; set; }
    
        public virtual DURUMLAR DURUMLAR { get; set; }
        public virtual T_PERSONEL T_PERSONEL { get; set; }
    }
}
