//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PERSONEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PERSONEL()
        {
            this.ISLER = new HashSet<ISLER>();
        }
    
        public int PERSONELID { get; set; }
        public string PERSONELADSOYAD { get; set; }
        public string PERSONELKULLANICIAD { get; set; }
        public string PERSONELPAROLA { get; set; }
        public Nullable<int> PERSONELBIRIMID { get; set; }
        public Nullable<int> PERSONELYETKIID { get; set; }
    
        public virtual BIRIMLER BIRIMLER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISLER> ISLER { get; set; }
        public virtual YETKI_TURLERI YETKI_TURLERI { get; set; }
    }
}
